### ISSUE TITLE
[adangert/BitcoinCashWallet]: Show balance also in selected currency

### ISSUE THREAD

**Issue by chaintip** [chaintip/bounties#21]
**Repository**: **[adangert/BitcoinCashWallet](http://github.chaintip.org/adangert/BitcoinCashWallet)**
**Issue [#8](http://github.chaintip.org/adangert/BitcoinCashWallet/issues/8)**: **Show balance also in selected currency**

***
**Total Bounty**: `0.00396228 BCH`| `~   5.14 USD`

To claim this bounty, get a pull request merged with ```@chaintip fixes #8``` in the creation comment.

**On-Chain Tips**:
- `0.00396228 BCH`| `~   5.14 USD` [from](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld4xkdja43s0te5sc064eapdycpj4v9l0h6k7z) **block-spider** to return to sender in 1 hour from now.

***
**Pull Requests Fixing Issue**:
- [PR [#15](http://github.chaintip.org/adangert/BitcoinCashWallet/pull/15) - fixed issue] chaintip fixes #8

**Comment by adangert** [comment]
the pull request was merged in.

**Comment by adangert** [comment]
it looks like the PR was merged after the comment was updated to include @chaintip and thus the bounty did not go through

**Comment by chaintip** [comment]
You can't tip a bounties issue... it creates all sorts of confusion :)

**Comment by chaintip** [comment]
I see, did you create the PR and merge it in a matter of seconds? I'm trying to work out what went wrong.

**Comment by chaintip** [comment]
Ok, I marked it as unmerged in my database and then created a 'manual notification' so that it got processed. I'll add an issue about the timing issue. Do you remember how many seconds you waited from PR creation to PR merge?

**Comment by adangert** [comment]
Yeah I created the PR, forgot the @ in the comment, merged it probably after like 10 seconds, then edited the comment to include the @ symbol, the chain tip bot then responded that once the PR was merged the bounty would go through, even though it was already merged.

**Comment by adangert** [comment]
The problem may be the edit of the comment to include the @ symbol

**Comment by chaintip** [comment]
Ok, I don't cater for that but probably should. Thanks!
