### ISSUE TITLE
Doesn't return funds after expire time

### ISSUE THREAD

**Issue by stanfieldr** [chaintip/bounties#49]
https://github.com/chaintip/talking-in-public/issues/268

**Comment by chaintip** [comment]
hey @stanfieldr, ChainTip has not been functional since the BSV fork... I'm working to put it back up now... been having some trouble getting nodes running again etc.

**Comment by chaintip** [comment]
hey @stanfieldr, getting it back up this weekend, please see https://github.com/chaintip/chaintip-github/issues/37

Sorry to hijack your cash for sooo long!

**Comment by chaintip** [comment]
@stanfieldr, got it back up now... I've manually tipped you the amount here... again apologies for taking so long to get this back to you!

https://github.com/chaintip/chaintip-github/issues/37#issuecomment-554798290
